# Generated by Django 3.1.3 on 2020-11-21 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Razão Social')),
                ('trading_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('registered_number', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('employees', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Funcionários')),
            ],
            options={
                'ordering': ['name', 'trading_name'],
            },
        ),
    ]
