# Generated by Django 3.1.3 on 2020-11-22 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Funcionários'),
        ),
    ]
