# Generated by Django 3.1.3 on 2020-11-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20201122_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
    ]
